In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [13]:
row=3
col=3
arr2=[[j for j in range(col)] for i in range(row)]
arr2

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [15]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [16]:
array_1=[1,2,3]
array_2=[4,5,6]
array_3=[7,8,9]

arr_3d=np.array([array_1,array_2,array_3])
arr_3d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
array_1=[1,2,3]
array_2=[4,5,6]
array_3=[7,8,9]
array_4=[10,11,12]

array_4d=np.array([array_1,array_2,array_3,array_4])
array_4d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [19]:

start = 0
stop = 10
num_points = 4

array = np.linspace(start, stop, num_points)
print(array)


[ 0.          3.33333333  6.66666667 10.        ]


In [20]:
length = 10
zeros_array = np.zeros(length)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
length=5
ones_arr=np.ones(length)
print(ones_arr)

[1. 1. 1. 1. 1.]


In [26]:
length=5
random=np.random.rand(length)
print(random)

[0.46153407 0.78418922 0.92233984 0.52244748 0.34886062]


In [27]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [28]:
print(arr[0])

1


In [29]:
print(arr[1])

2


In [34]:
print(arr[0:3])

[1 2 3]


In [35]:
print(arr[1:])

[2 3 4 5]


In [36]:
print(arr[2:])

[3 4 5]


In [37]:
row=3
col=3
arr2=[[j for j in range(col)] for i in range(row)]
arr2

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [38]:
print(arr2[0][1])

1


In [47]:
for i in range(0,3):
    print(arr2[i][2])

2
2
2


In [49]:
for i in range(0,3):
    rangen=range(arr2[1][i],arr2[2][i])
print(rangen)

range(2, 2)


In [52]:
arr=np.array([5,6,2,8])
sortarr=np.sort(arr,axis=0)
print(sortarr)

[2 5 6 8]
